# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [1]:
import numpy as np

# Create a NumPy array of shape (5, 5) filled with random integers

array=np.random.randint(1,21, size=(5,5))
print("Original Array: ")
print(array)

# Replace all the elements in the third column with 1.

array[:,2]=1
print("Modified Array: ")
print(array)

Original Array: 
[[19 14  4 20  7]
 [ 6  2 13  9 14]
 [12 13 18  2 15]
 [14 20 13 12 12]
 [18 18 14 13 11]]
Modified Array: 
[[19 14  1 20  7]
 [ 6  2  1  9 14]
 [12 13  1  2 15]
 [14 20  1 12 12]
 [18 18  1 13 11]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [7]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16
array=np.arange(1,17).reshape((4,4))
print("original_array:")
print(array)

# Replace the diagonal elements with 0
np.fill_diagonal(array,0)
print("Modified Array: ")
print(array)


original_array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified Array: 
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [9]:
# Create a NumPy array of shape (6, 6) with values from 1 to 36

array=np.arange(1,37).reshape((6,6))
print("Original Array: ")
print(array)

# Extract the sub-array 
sub_array=array[2:5,1:4]
print("Sub Array: ")
print(sub_array)

Original Array: 
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub Array: 
[[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [12]:
# Create a NumPy array of shape (5, 5) with random integers
array=np.random.randint(1,21, size=(5,5))
print("Random_Numbers: ")
print(array)

# Extract the elements on the border
border_elements=np.concatenate((array[0,:], array[-1,:], array[1:-1,0],array[1:-1,-1]))
print("Border Elements: ")
print(border_elements)

Random_Numbers: 
[[11 10  8  4  7]
 [ 7  9  8 14  6]
 [13 14 16 16 18]
 [18 20 11 14  1]
 [ 5 15  4 11 14]]
Border Elements: 
[11 10  8  4  7  5 15  4 11 14  7 13 18  6 18  1]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [19]:
# Create two NumPy arrays of shape (3, 4) filled with random integers.
array1=np.random.randint(1,13, size=(3,4))
array2=np.random.randint(1,13,size=(3,4))
print("Array1: ")
print(array1)
print("Array2:")
print(array2)

# Perform element-wise addition, subtraction, multiplication, and division.
addition=array1+array2
print("addition: ", addition)
subtraction=array1-array2
print("subtraction: ", subtraction)
multiplication=array1*array2
print("multiplication: ", multiplication)
division=array1/array2
print("division: ", division)

Array1: 
[[ 1 12  4  9]
 [12  7  4  3]
 [10  5  7 10]]
Array2:
[[ 9 10  9  9]
 [ 6  2  9  4]
 [ 6 10  7  6]]
addition:  [[10 22 13 18]
 [18  9 13  7]
 [16 15 14 16]]
subtraction:  [[-8  2 -5  0]
 [ 6  5 -5 -1]
 [ 4 -5  0  4]]
multiplication:  [[  9 120  36  81]
 [ 72  14  36  12]
 [ 60  50  49  60]]
division:  [[0.11111111 1.2        0.44444444 1.        ]
 [2.         3.5        0.44444444 0.75      ]
 [1.66666667 0.5        1.         1.66666667]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [21]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16.
array=np.arange(1,17).reshape((4,4))
print("Original Array: ")
print(array)

# Compute the row-wise and column-wise 
row_wise=np.sum(array,axis=1)
column_wise=np.sum(array,axis=0)
print("Row Wise Sum: ")
print(row_wise)
print("Column Wise Sum: ")
print(column_wise)

Original Array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row Wise Sum: 
[10 26 42 58]
Column Wise Sum: 
[28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [25]:
# Create a NumPy array of shape (5, 5) filled with random integers
array=np.random.randint(1,26, size=(5,5))
print("Original Array: ")
print(array)

# Compute the mean, median, standard deviation, and variance of the array.
mean=np.mean(array)
print("Mean: ")
print(mean)

median=np.median(array)
print("Median: ")
print(median)

std_dev=np.std(array)
print("Standard Deviation: ")
print(std_dev)

Variance=np.var(array)
print("Variance: ")
print(Variance)

Original Array: 
[[ 5 19 23 14 18]
 [25 16  5  3 16]
 [10 25 10  7 13]
 [ 9  1  2 16  7]
 [19 19  5 25 11]]
Mean: 
12.92
Median: 
13.0
Standard Deviation: 
7.375201692157307
Variance: 
54.393600000000006


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [28]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9. 
array=np.arange(1,10).reshape((3,3))
print("Original Array: ")
print(array)

# Normalize the array 
mean=np.mean(array)
std_dev=np.std(array)
normalize_array=(array-mean)/std_dev
print("Normalized Array: ")
print(normalize_array)

Original Array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized Array: 
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [32]:
# Create a NumPy array of shape (3, 3) filled with random integers.
array=np.random.randint(1,11, size=(3,3))
row_array=np.random.randint(1,11, size=(3,))
print("Original Array")
print(array)
print("1D Array: ")
print(row_array)

# Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
result_array=array+row_array
print("Result Array: ")
print(result_array)

Original Array
[[ 1  8 10]
 [ 9  9  6]
 [ 1  1  5]]
1D Array: 
[5 3 5]
Result Array: 
[[ 6 11 15]
 [14 12 11]
 [ 6  4 10]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [34]:
array=np.random.randint(1,18, size=(4,4))
row_array=np.random.randint(1,18, size=(4,))
print("Original Array")
print(array)
print("Row Array: ")
print(row_array)

result=array-row_array
print("Result Array")
print(result)

Original Array
[[10 11  6  7]
 [ 7  1  6  7]
 [11 15 11 16]
 [ 5  8 15  6]]
Row Array: 
[17 15  7 15]
Result Array
[[ -7  -4  -1  -8]
 [-10 -14  -1  -8]
 [ -6   0   4   1]
 [-12  -7   8  -9]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [35]:
# Create a NumPy array of shape (3, 3) representing a matrix.
array=np.random.randint(1,11, size=(3,3))
print("Array: ")
print(array)

# Compute the determinant
determinant=np.linalg.det(array)
print("Determinant")
print(determinant)

# Compute the inverse
inverse=np.linalg.inv(array)
print("Inverse: ")
print(inverse)

# Compute the eigenvalues
eigenvalues=np.linalg.eigvals(array)
print("Eigenvalues: ")
print(eigenvalues)


Array: 
[[2 7 7]
 [4 8 3]
 [3 3 3]]
Determinant
-74.99999999999997
Inverse: 
[[-0.2         0.          0.46666667]
 [ 0.04        0.2        -0.29333333]
 [ 0.16       -0.2         0.16      ]]
Eigenvalues: 
[13.47747515 -2.60977873  2.13230358]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [37]:
# Create two NumPy arrays of shape (2, 3) and (3, 2).
array1=np.random.randint(1,8, size=(2,3))
print("Array 1: ", array1)
array2=np.random.randint(1,8, size=(3,2))
print("Array2: ", array2)

# Perform matrix multiplication on these arrays.
result=np.dot(array1,array2)
print("Matrix Multiplication: ", result)

Array 1:  [[4 5 4]
 [3 6 7]]
Array2:  [[4 5]
 [5 2]
 [3 1]]
Matrix Multiplication:  [[53 34]
 [63 34]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [11]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9.
array=np.arange(1,10).reshape((3,3))
print("Original Array: ")
print(array)

# Reshape the array to shape (1, 9) 
reshaped_array=array.reshape((1,9))
print("Reshaped Array: ")
print(reshaped_array)

# Then to shape (9, 1).
shaped=reshaped_array.reshape((9,1))
print("Shaped: ", shaped)

Original Array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped Array: 
[[1 2 3 4 5 6 7 8 9]]
Shaped:  [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [14]:
# Create a NumPy array of shape (5, 5) filled with random integers
array=np.random.randint(1,27, size=(5,5))
print("Original Array: ")
print(array)

# Flatten the array 
flattened_array=array.flatten()
print("Flatened Array: ", flattened_array)

# then reshape it back to (5, 5).
reshaped_array=flattened_array.reshape((5,5))
print("Reshaped Array: \n", reshaped_array)

Original Array: 
[[23  8  3 20  4]
 [ 9 26 21  7 22]
 [12 20  7  7 25]
 [22  2  1 17 12]
 [22  1 17 19 11]]
Flatened Array:  [23  8  3 20  4  9 26 21  7 22 12 20  7  7 25 22  2  1 17 12 22  1 17 19
 11]
Reshaped Array: 
 [[23  8  3 20  4]
 [ 9 26 21  7 22]
 [12 20  7  7 25]
 [22  2  1 17 12]
 [22  1 17 19 11]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [19]:
# Create a NumPy array of shape (5, 5) filled with random integers.
array=np.random.randint(1,27, size=(5,5))
print("Original Array: \n", array)

# Use fancy indexing to extract the elements at the corners of the array.
corners=array[[0,0,-1,-1],[0,-1,0,-1]]
print("Corner_element: \n", corners)

Original Array: 
 [[ 5  5 26 21 13]
 [ 1 12 16 21 14]
 [ 2 12  8 11  2]
 [ 3 15 24  4 10]
 [23 26  3  1 13]]
Corner_element: 
 [ 5 13 23 13]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [22]:
# Create a NumPy array of shape (4, 4) filled with random integers.
array=np.random.randint(1,18, size=(4,4))
print("Original Array: \n", array)

# Use boolean indexing to set all elements greater than 10 to 10.
array[array>10]=10
print("Modified Array: \n", array)

Original Array: 
 [[ 1 17 14 11]
 [16 12  5  6]
 [16  8 17  2]
 [13  6  2 12]]
Modified Array: 
 [[ 1 10 10 10]
 [10 10  5  6]
 [10  8 10  2]
 [10  6  2 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [25]:
# Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float)
data_type=[('name','U10'),('age','i4'),('weight','f4')]
data=np.array([('Alice',25,55.5),('Bob', 26, 50.5),('Charlie', 25, 65.3)], dtype=data_type)
print("Original Array: ", data)

# sort the array by age.
sorted_data=np.sort(data, order='age')
print("Sorted Data: \n", sorted_data)

Original Array:  [('Alice', 25, 55.5) ('Bob', 26, 50.5) ('Charlie', 25, 65.3)]
Sorted Data: 
 [('Alice', 25, 55.5) ('Charlie', 25, 65.3) ('Bob', 26, 50.5)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [27]:
# Create a structured array
data_type=[('x','i4'),('y','i4')]
data=np.array([(1,2),(3,4),(5,6)], dtype=data_type)
print("Original Array: ", data)

# compute the Euclidean distance between each pair of points.
distance=np.sqrt((data['x'][:,np.newaxis]- data['x'])**2 + (data['y'][:,np.newaxis]-data['y'])**2)
print("Euclidean Distance", distance)

Original Array:  [(1, 2) (3, 4) (5, 6)]
Euclidean Distance [[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [28]:
import numpy.ma as ma

# Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10.
array=np.random.randint(1,18, size=(4,4))
masked_array= ma.masked_greater(array,10)
print("Original array: ", array)
print("Masked Array: ", masked_array)

# Compute the sum of the unmasked elements.
sum_unmasked=masked_array.sum()
print("Unmasked Sum: ", sum_unmasked)

Original array:  [[ 2 16 16  6]
 [ 7  3 15 12]
 [15  3  8  2]
 [17 12  4  2]]
Masked Array:  [[2 -- -- 6]
 [7 3 -- --]
 [-- 3 8 2]
 [-- -- 4 2]]
Unmasked Sum:  37


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [33]:
# Create a masked array of shape (3, 3) with random integers and mask the diagonal elements.
array=np.random.randint(1,21, size=(3,3))
masked_array=ma.masked_array(array,mask=np.eye(3, dtype=bool))
print("Original Array: \n", array)
print("Masked Array: \n", masked_array)

# Replace the masked elements with the mean of the unmasked elements.
unmasked_mean=masked_array.mean()
masked_array=masked_array.filled(unmasked_mean)
print("Modified Masked Array: \n", masked_array)

Original Array: 
 [[19  6 11]
 [14 19 18]
 [ 6  1 18]]
Masked Array: 
 [[-- 6 11]
 [14 -- 18]
 [6 1 --]]
Modified Masked Array: 
 [[ 9  6 11]
 [14  9 18]
 [ 6  1  9]]
